apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wakapi.fullname" . }}-config-map
data:
  config.yml: |-
    {{- with .Values.wakapi_config }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
